### PR TITLE
Update UI of Backbone Debugger

### PR DESCRIPTION
**Pull request by jakejarrett**
This implements a new theme for Backbone debugger, tailored more toward a Material design (With pieces based on VueJS's debugger design)

## Widescreen
screenshot from 2017-01-10 18-32-46

## Tall Display
screenshot from 2017-01-10 18-43-30

### CODE REVIEW

**Comment by Maluen** [comment]
Cool theme! I'm totally ok with merging it in, however we have to solve some issues first:

1) The main container becomes blank when devtools width is <= 532 px, which is when the top navbar elements start to stack

image

2) Vertical scrollbar doesn't show all content:

image

3) Collapse / Uncollapse / Search / Sort buttons don't work in widescreen, i.e. when they are moved in the topbar:

image

- "Load more" link bug:
  - Resize devtools so that the search feature is usable (see previous issue)
  - Search something that doesn't exist, so to get the "No results" screen
  - Clear the search input

image

4) Sort dropdown z-index issue. You can see how the bottom border isn't visible:

image

Also, would be cool to add an hover effect by changing background color of component headers when hovering on them. We had this in the previous design.

**Comment by jakejarrett** [comment]
Updated with those changes except for 4, Which i don't believe is introduced in these changes, it appears to be the outline that gets affected by the options. (It may not contribute to the height of the select?)

Screenshot of both versions with the select open & Outline color set to blue.
screenshot from 2017-01-11 08-52-00
screenshot from 2017-01-11 08-49-46

**Comment by Maluen** [comment]
>Updated with those changes except for 4, Which i don't believe is introduced in these changes, it appears to be the outline that gets affected by the options. (It may not contribute to the height of the select?)

Makes sense, I confirm it also happens in the existing theme, we can live with it.

We are close to merging, only thing I see for now is a ugly visual effect in small widths:

image

5) We should stack the "this", "Status", "Attributes", etc. (i..e the component properties), similarly to the old theme, in case of small widths.

6) In the top navbar, "Options" remains fixed on top right, while the first entries fall on the next line.
I guess it would be better if instead it worked the other way around, i.e. Options goes on the next line, then Routers to its left, then Collections to the left of Routers and so on.
Probably not the best explanation, but I hope you got my point.

**Comment by agwidarsito** [comment]
This layout is great - can't wait for the merge! 👍

**Comment by jakejarrett** [comment]
Pushed with those fixes :smile_cat:

**Comment by Maluen** [comment]
Merged! Great work 😄

I'm going to push a new release to chrome webstore after updating the screenshots.

**Comment by Maluen** [comment]
Deployed to chrome webstore.

**Comment by jakejarrett** [comment]
:smile: Dope! Thanks for merging.

**Pull request merged**
